export const SET_MODULE_AREAS = 'SET_MODULE_AREAS';
export const SET_FILTER_FORM_DATA = 'SET_FILTER_FORM_DATA';
export const SET_FORM_DATA = 'SET_FORM_DATA';
export const CLOSE_FORM = 'CLOSE_FORM';
export const SAVE_FORM_DATA = 'SAVE_FORM_DATA';
export const SET_PARENT_DATA = 'SET_PARENT_DATA';
export const SET_PARENT_INFO = 'SET_PARENT_INFO';
export const USAGE = 'USAGE'
export const USAGE_SUCCESS = 'USAGE_SUCCESS'
export const USAGE_FAILED = 'USAGE_FAILED'
export const SET_ENVIRONMENT = 'SET_ENVIRONMENT'

