export const GET_FAVORITE_LINKS = 'getFavoriteLinks';
export const SAVE_FAVORITE_LINKS = 'saveFavoriteLinks';

export const FETCH_FAVORITE_LINKS_PENDING = "FETCH_FAVORITE_LINKS_PENDING";
export const FETCH_FAVORITE_LINKS_SUCCESS = "FETCH_FAVORITE_LINKS_SUCCESS";
export const FETCH_FAVORITE_LINKS_ERROR = "FETCH_FAVORITE_LINKS_ERROR";


export const FETCH_LINKS_PENDING = 'FETCH_LINKS_PENDING';
export const FETCH_LINKS_SUCCESS = 'FETCH_LINKS_SUCCESS';
export const FETCH_LINKS_ERROR = 'FETCH_LINKS_ERROR';

