export const GET_USER_DATA_QUERIES = '/UserDataQueriesService/userDataQueries';
export const GET_CUSTOM_PAYMENTS_LIST = '/PaymentsService/getCustomPaymentList';
export const GET_CUSTOM_TAX_CODES = '/TaxCodeService/getCustomTaxCodesList';
export const GET_ALL_POPULATED_V3_STATES = '/UserDataQueriesService/getAllPopulatedV3States';
export const GET_EXPERIENCE_RATES = '/UserDataQueriesService/userDataQueries';
export const GET_RESIDENT_STATE_AUTOCOMPLETE_MOCKDATA = '/UserDataQueriesService/getResidentState';
export const GET_SAMPLE_DATE_FIELD_DATA = '/UserDataQueriesService/filterDateFieldGridData';
export const GET_EXEMPT_MILITARY_LOCATION_AUTOCOMPLETE_MOCKDATA = '/UserDataQueriesService/getExemptmilitaryLocation';
export const GET_PRINCIPAL_STATE_EMPLOYMENT_AUTOCOMPLETE_MOCKDATA ='/UserDataQueriesService/getPrincipalStateEmployment';
export const GET_SUPPLEMENTAL_INFO_FOR_TAX = '/UserDataQueriesService/userDataQueries';
export const GET_EXISTING_FAVORITE_LINKS = '/getExistingFavoriteLinks';
export const DELETE_EXISTING_FAVORITE_LINKS = '/deleteExistingFavoriteLinks';
export const INSERT_FAVORITE_LINK_RECORD = '/insertFavoriteLinkRecord';
export const GET_RECENT_USAGE = '/UsageDataService/getUsageData';
export const GET_CUSTOM_FORMULAS = '/TaxCodeService/getCustomTaxCodesList';
export const GET_COMPANIES = '/CompanyService/getCompanyList';
export const GET_WORKSITES = '/CompanyService/getCompanyList';
export const GET_WORKSITES_LOCATIONS = '/CompanyService/getWorksiteManagementLocationList';
export const GET_CUSTOM_TAX_FORMULAS = '/TaxCodeService/getCustomFormulaList';
export const GET_PA_SERVICES_TAX_REPORT = '/UserDataQueriesService/getPATaxReportAllAuthorities';
export const GET_TAX_HISTORY = '/UserDataQueriesService/getTaxHistoryReportAuthorities';
export const GET_TAX_HISTORY_REPORT = '/UserDataQueriesService/getTaxHistoryReportAuthority';
export const GET_PA_SERVICE_TAX_REPORT = '/UserDataQueriesService/getPATaxReportForAuthority';
export const SAVE_CUSTOM_FORMULA = '/TaxCodeService/saveCustomFormula';
export const DELETE_CUSTOM_FORMULA = '/TaxCodeService/deleteCustomFormula';
export const GET_ALL_TAXCODES_AUTOCOMPLETE = '/TaxCodeService/getAllTaxCodesAutocomplete';
export const GET_ALL_TAXTYPES_AUTOCOMPLETE = '/TaxCodeService/getAllTaxTypeAutocomplete';
export const GET_TAXCODES_AUTOCOMPLETE = '/TaxCodeService/getTaxCodesAutocomplete';
export const GET_TAXTYPES_AUTOCOMPLETE = '/TaxCodeService/getTaxTypeAutocomplete';
export const GET_TAXTYPES = '/TaxCodeService/getTaxTypes';
export const GET_PAYMENT_AUTOCOMPLETE_MOCKDATA = '/TaxCodeService/getPaymentAutoCompl';
export const GET_ALL_AUTHORITY_CODE_AUTOCOMPLETE = '/TaxCodeService/getAuthoritiesAutocomplete';
export const GET_PLACE_CODE_AUTOCOMPLETE = '/TaxCodeService/getPlaceCodeAutoCompl';
export const GET_SCHOOL_DISTRICT_AUTOCOMPLETE = '/TaxCodeService/getSchoolDistrictAutoCompl';
export const GET_GARNISMENT_FORMULA_AUTOCOMPLETE = '/TaxCodeService/getGarnishmenFormulaAutoCompl';
export const GET_GARNISMENT_GROUP_CODE_AUTOCOMPLETE = '/TaxCodeService/getGarnishmenGroupCodeAutoCompl';
export const GET_CUSTOM_GARNISMENT_FORMULA_AUTOCOMPLETE = '/UserDataQueriesService/getCustomGarnishmentFormulas';
export const GET_CUSTOM_GARNISMENT_FORMULAS = '/UserDataQueriesService/userDataQueries';
export const GET_CUSTOM_GARNISMENT_CODE_AUTOCOMPLETE = '/TaxCodeService/getCustomGarnishmentCodeAutoCompl';
export const GET_COUNTY_AUTOCOMPLETE = '/TaxCodeService/getCounty';
export const GET_GROUP_AUTOCOMPLETE = '/TaxCodeService/getGroup';
export const GET_UDQ_AUTOCOMPLETE = '/UserDataQueriesService/getAutocomplete';
export const GET_TAX_CODE_OVERRIDDEN_AUTOCOMPLETE_MOCKDATA = '/TaxCodeService/getTaxCodeOverriden';
export const GET_NON_RESIDENCE_TAX_TYPE_AUTOCOMPLETE_MOCKDATA = '/TaxCodeService/getNonResidenceTaxType';
export const GET_RESIDENCE_TAX_TYPE_AUTOCOMPLETE_MOCKDATA = '/TaxCodeService/getResidenceTaxType';
export const GET_TAX_CODE_RECIPROCATE_AUTOCOMPLETE_MOCKDATA = '/TaxCodeService/getTaxCodeReciprocate';
export const GET_PAYMENT_CODE_AUTOCOMPLETE_MOCKDATA = '/TaxCodeService/getPaymentCode';
export const GET_USER_TAX_CODE_AUTOCOMPLETE_MOCKDATA = '/TaxCodeService/getUserTaxCode';
export const GET_CUSTOM_TYPEOF_DATA = '/TaxCodeService/getPmtCodesAutocomplete';
export const GET_TYPEOF_DATA = '/UserDataQueriesService/getAutocomplete';
export const GET_TAX_CODE_UDQ_AUTOCOMPLETE_MOCKDATA = '/TaxCodeService/getTaxCode';
export const GET_CALCULATION_METHOD_AUTOCOMPLETE_MOCKDATA = '/TaxCodeService/getCalculationMethod';
export const GET_WAGE_REPORTING_METHOD_AUTOCOMPLETE_MOCKDATA = '/TaxCodeService/getWageReportingmethod';
export const DELTE_CUSTOM_PAYMENT = '/TaxCodeService/deleteCustomPayment';
export const DELETE_CUSTOM_TAX_CODES = '/TaxCodeService/deleteCustomTaxCode';
export const SAVE_CUSTOM_PAYMENT = '/PaymentsService/saveCustomPayment';
export const SAVE_CUSTOM_TAX_CODES = '/TaxCodeService/saveCustomTaxCode';
export const SAVE_CUSTOM_FORMULAS = '/TaxCodeService/saveCustomTaxCode';
export const SAVE_WORKSITES_LOCATIONS = '/CompanyService/saveWksiteMgmtLocation';
export const SAVE_WORKSITES = '/CompanyService/saveWorksiteManagementList';
export const GET_CUSTOM_TAXCODES_AUTOCOMPLETE = '/TaxCodeService/getCustomTaxCodesAutocomplete';
export const SAVE_COMPANY = '/CompanyService/saveCompany';
export const DELETE_COMPANY = '/CompanyService/deleteCompany';
export const GET_CUSTOM_GARNISHMENT_CODES = '/GarnishmentService/getCustomGarnishmentList';
export const SAVE_CUSTOM_GARNISHMENT_CODE = '/GarnishmentService/saveCustomGarnishment';
export const DELETE_CUSTOM_GARNISHMENT_CODE = '/GarnishmentService/deleteCustomGarnishment';
export const GET_EMPLOYEE_GROUPS = '/EmployeeService/getEmployeeGroupList';
export const SAVE_EMPLOYEE_GROUP = '/EmployeeService/saveEmployeeGroup';
export const DELETE_EMPLOYEE_GROUP = '/EmployeeService/deleteEmployeeGroup';
export const GET_GARNISHMENT_GROUPS = '/GarnishmentService/getGarnishmentGroupList';
export const DELETE_GARNISHMENT_GROUP = '/GarnishmentService/deleteGarnishmentGroup';
export const SAVE_GARNISHMENT_GROUP = '/GarnishmentService/saveGarnishmentGroup';
export const GET_TAX_EFFECTIVE_DATE_OVERRIDES = '/TaxCodeService/getTaxEffectiveDateOverrides';
export const DELETE_TAX_EFFECTIVE_DATE_OVERRIDE = '/TaxCodeService/deleteTaxEffectiveDateOverride';
export const SAVE_TAX_EFFECTIVE_DATE_OVERRIDE = '/TaxCodeService/saveTaxEffectiveDateOverride';
export const GENERATE_MARITAL_REPORT = '/UserDataQueriesService/generateMaritalStatusReport';
export const GENERATE_BATCH_TEST_REPORT = '/FileUploaderService/uploadBatchTest';
export const DELETE_WORKSITES_LOCATIONS = '/CompanyService/deleteWksiteMgmtLocation';
export const SAVE_SUPPRESS_MESSAGES = '/MessageSuppress/saveMessagesToSuppress';
export const GET_SUPPRESSED_MESSAGES = '/MessageSuppress/getSuppressedMessages';
export const GARNISHMENT_FORMULAS_OVERRIDE = '/GarnishmentOverrite/getFormulasOverride';
export const GARNISHMENT_FORMULA_OVERRIDES = '/GarnishmentService/getGarnishmentFormulaOverrides';
export const GET_DATASETS = '/getDataSEts';
export const GET_PERMISSIONS = './GET_PERMISSIONS';
export const SAVE_PERMISSIONS = './SAVE_PERMISSIONS';
export const PERMISSION_FOR = './PERMISSION_FOR';
export const CUSTOM_GARNISHMENT_FORMULA = './CUSTOM_GARNISHMENT_FORMULA';
export const GARNISHMENT = './GARNISHMENT';
export const AUTHORITY_NAME = './AUTHORITY_NAME';
export const GET_MESSAGE_VIEWER = '/MessageService/getMessageRunList'
export const GET_MESSAGES_VIEWER = '/MessageService/getMessageViewListByRunId'
export const GET_MESSAGES_VIEWER_TYPE = '/MessageService/getMessageViewListByMessageType'
export const GET_MESSAGES_RUN_LIST_BY_DATE = '/MessageService/getMessageRunListByFilterDate'
export const DELETE_ALL_MESSAGES = '/MessageService/deleteAllMessages'
export const DELETE_ALL_MESSAGES_BY_RUN_ID = '/MessageService/deleteAllMessagesByRunId'
export const WHAT_IF_EMP='/WhatIfService/getWhatIfEmployees'
export const SAVE_WHATIF_EMP='/WhatIfService/saveWhatIfEmployee'
export const WHAT_IF_TAXES='/WhatIfService/getWhatIfTaxes'
export const WHAT_IF_GARNISHMENTS='/WhatIfService/getWhatIfEmployeeGarnishments'
export const WHAT_IF_DEDUCTION_BENEFITS='/WhatIfService/getWhatIfEmployeeGarnDedBenefits'
export const SAVE_WHAT_IF_DEDUCTION_BENEFITS='/WhatIfService/saveUpdateWhatIfEmployeeGarnDedBenefits'
export const GET_BENEFITS_PLANS = '/WhatIfService/getWhatIfGarnDedBenefitsAutocomplete'
export const TAX_LOCATOR='./_taxLocator_MockData.json'
export const WHAT_IF_LOCATIONS= '/TaxLocatorService/getTaxLocatorEmployeeLocations'
export const WAGE_CODE_DESC = '/WhatIfService/getWhatIfEmployeeWageAutocomplete'
export const GET_PENSION_WHAT_IF = '/WhatIfService/getPensionWhatIfEmployees'
export const GET_WHAT_IF_WAGES = '/WhatIfService/getWhatIfEmployeeWages'
export const DELETE_WAGE_DETAILS = '/WhatIfService/deleteWhatIfEmployeeTaxWage'
export const SAVE_WAGE_DETAILS = '/WhatIfService/saveWhatIfEmployeeTaxWage'
export const GET_WHAT_IF_EMPLOYEES = '/WhatIfService/getWhatIfEmployees'
export const GET_TAX_LOCATOR = '/TaxLocatorService/getTaxLocatorEmployees'
export const GET_RUN_LOCATOR_SERVICE = '/TaxLocatorService/runTaxLocator'
export const GET_ADRRESS_FROM_WORKSITES = '/TaxLocatorService/getTaxLocatorAddressFromWorksite'
export const DELETE_GARN_DED_BENEFITS='/WhatIfService/deleteWhatIfEmployeeGarnDedBenefits'
export const SAVE_WHATIF_GARNISHMENT='/WhatIfService/saveWhatIfEmployeeGarnishment'
export const DELETE_WHATIF_GARNISHMENT='/WhatIfService/deleteWhatIfEmployeeGarnishment'
export const SAVE_ADDRESS_FROM_WORKSITES = '/TaxLocatorService/saveWorksitesToTaxLocator'
export const SAVE_TAX_LOCATOR = '/TaxLocatorService/saveTaxLocatorEmployee'
export const SAVE_AS_TAX_LOCATOR = '/TaxLocatorService/saveAsTaxLocatorEmployee'
export const DELETE_TAX_LOCATOR = '/TaxLocatorService/deleteTaxLocatorEmployee'
export const DELETE_WHATIF_LOCATIONS = '/TaxLocatorService/deleteTaxLocatorEmployeeLocation'
export const VIEW_PDF_TAX_LOCATOR = '/TaxLocatorService/generateTaxLocatorEmployeePDF'
export const VIEW_PDF_RUN_LOCATOR_SERVICE = '/TaxLocatorService/generateTaxLocatorRunLocatorPDF'
export const SAVE_MANAGE_LOCATIONS = '/TaxLocatorService/saveTaxLocatorEmployeeLocation'
export const GET_GROUP_OVERRIDE = '/EmployeeService/getGroupOverrides'
export const GET_GROUP_OVERRIDES = '/EmployeeService/getEmployeeGroupList'
export const GROUP_OVERRIDE_AUTHORITY = '/EmployeeService/getGroupOverrideAutocompleteAuth'
export const GROUP_OVERRIDE_FORMULA = '/EmployeeService/getGroupOverrideAutocompleteFormulas'
export const VIEW_PDF_GROUP_OVERRIDE = '/EmployeeService/generateGroupOverridesPDF'
export const SAVE_GROUP_OVERRIDE = '/EmployeeService/saveGroupOverride'
export const DELETE_GROUP_OVERRIDE = '/EmployeeService/deleteGroupOverride'
export const DELETE_WHAT_IF_EMPLOYEES = '/WhatIfService/deleteWhatIfEmployee'
export const DELETEALL_WHAT_IF_EMPLOYEES = '/WhatIfService/deleteAllWhatIfEmployees'
export const WHATIF_GARN_AUTOCOMPLETE_AUTHS= '/TaxCodeService/getAutocompleteAuthorities'
export const WHATIF_GARN_AUTOCOMPLETE_TAXTYPES= '/WhatIfService/getWhatIfGarnAutocompleteTaxTypes'
export const WHATIF_GARN_AUTOCOMPLETE_FORMULAS='/WhatIfService/getWhatIfAutocompleteFormulas'
export const GET_PAYMENT_OVERRIDE = '/PaymentsService/getPaymentOverrideList'
export const DELETE_PAYMENT_OVERRIDE ='/PaymentsService/deletePaymentOverride'
export const SAVE_PAYMENT_OVERRIDE ='/PaymentsService/savePaymentOverride'
export const GET_ADDRESS_OVERRIDES = '/TaxCodeService/getAddressOverrides'
export const DELETE_ADDRESS_OVERRIDES='/TaxCodeService/deleteAddressOverride'
export const SAVE_ADDRESS_OVERRIDES='/TaxCodeService/saveAddressOverride'
export const GET_REDUNDANT_ADDRESS_OVERRIDES='/TaxCodeService/getRedundantAddressOverrides'
export const GENERATE_WHATIF_EMPLOYEE_DETAIL_PDF = '/WhatIfService/generateWhatIfEmployeeDetailPDF'
export const GET_UM_EMPLOYMENT_OVERRIDE_LIST ='/TaxCodeService/getUnempOverrideList'
export const GET_UM_EMPLOYMENT_OVERRIDE_DELETE='/TaxCodeService/deleteUnemploymentOverride'
export const GET_UM_EMPLOYMENT_OVERRIDE_SAVE='/TaxCodeService/saveUnemploymentOverride'
export const GET_CUSTOM_GARNISHMENT_FORMULAS='/GarnishmentService/getCustomGarnishmentFormulasList'
export const GET_WHATIF_AUTOCOMPLETE_TAXTYPES='/WhatIfService/getWhatIfAutocompleteTaxTypes'
export const DELETE_WHATIF_EMPLOYEE_TAX='/WhatIfService/deleteWhatIfEmployeeTax'
export const SAVE_WHATIF_EMPLOYEE_TAX='/WhatIfService/saveWhatIfEmployeeTax'
export const GET_RECIPROCAL_OVERRIDES= '/EmployeeService/getEmployeeGroupList'
export const GET_RECIPROCAL_OVERRIDE= '/TaxCodeService/getReciprocalOverrideList'
export const GET_TAX_CODE_TOBE_OVERRIDEN_STATE = '/TaxCodeService/getRecipOvrdAutocompleteResAuthorities'
export const GET_RESIDENT_TAX_TYPE_STATE = '/TaxCodeService/getRecipOvrdAutocompleteResTaxTypes'
export const GET_TAX_CODE_TO_RECIPROCATE_STATE = '/TaxCodeService/getRecipOvrdAutocompleteNonResAuthorities'
export const GET_NON_RESIDENT_TAX_TYPE_STATE = '/TaxCodeService/getRecipOvrdAutocompleteNonResTaxTypes'
export const GET_TAX_CODE_TOBE_OVERRIDEN_LOCAL = '/TaxCodeService/getRecipOvrdAutocompleteResAuthoritiesLocal'
export const GET_RESIDENT_TAX_TYPE_LOCAL = '/TaxCodeService/getRecipOvrdAutocompleteResTaxTypesLocal'
export const GET_TAX_CODE_TO_RECIPROCATE_LOCAL = '/TaxCodeService/getRecipOvrdAutocompleteNonResAuthoritiesLocal'
export const GET_NON_RESIDENT_TAX_TYPE_LOCAL = '/TaxCodeService/getRecipOvrdAutocompleteNonResTaxTypesLocal'
export const DELETE_RECIPROCAL_OVERRIDE = '/TaxCodeService/deleteReciprocalOverride'
export const SAVE_RECIPROCAL_OVERRIDE = '/TaxCodeService/saveReciprocalOverride'
export const GET_CONNECT_TO_DATA_SETS = '/TaxCodeService/saveReciprocalOverride'
export const DELETE_GARNISHMENT_FORMULA_OVERRIDE = '/GarnishmentService/deleteGarnishmentFormulaOverride'
export const GET_GARN_FORMULA_OVERD_TAXTYPE_AUTOCOMP=  '/GarnishmentService/getGarnFormulaOverdTaxTypeAutocomplete'
export const SAVE_GARNISHMENT_FORMULA_OVD = '/GarnishmentService/saveGarnishmentFormulaOverride'
export const GARNISHMENT_FORMULA_OVERRIDE_PDF ='/GarnishmentService/generateGarnishmentFormulaOverridePDF'
export const GET_OPTIONAL_RATE_OVERRIDES='/CompanyService/getOptionalRateOverrides'
export const GET_OPTIONAL_RATE_OVRD_AUTO_COMP_AUTH='/CompanyService/getOptionalRateOvrdAutocompleteAuth'
export const GET_OPTIONAL_RATE_OVRD_AUTO_COMP_TAXT='/CompanyService/getOptionalRateOvrdAutocompleteTaxTypes'
export const GET_OPTIONAL_RATE_OVRD_AUTO_COMP_FORM ='/CompanyService/getOptionalRateOvrdAutocompleteFormulas'
export const GET_OPTIONAL_RATE_OVRD_BSI_WAGE='/CompanyService/calculateBsiWage'
export const DELETE_OPTIONAL_RATE_OVERRIDE ='/CompanyService/deleteOptionalRateOverride'
export const SAVE_OPTIONAL_RATE_OVERRIDE='/CompanyService/saveOptionalRateOverride'
export const GET_CUSTOM_BACKUP_RESTORE= './_custombackupRestore_MockData.json'
export const GET_CUSTOM_DATA_BACKUP= './_customdataBackup_MockData.json'
export const GET_CUSTOM_DATA_RESTORE= './_customdataRestore_MockData.json'
export const GET_OPTIONAL_UNEMPLOYMENT_BACKUP= './_optionalBackup_MockData.json'
export const GET_OPTIONAL_UNEMPLOYMENT_RESTORE = './_optionalRestore_MockData.json'
export const GENERATE_DATABASE_LOAD = './_databaseLoad_MockData.json'
export const SAVE_CUSTOM_DATA_BACKUP = './_customdataBackup_MockData.json'
